export const cuisineTypePhoto = {
  Bengali: "https://i.ibb.co/35kxf0Ft/bengali.webp",
  Indian: "https://i.ibb.co/23FS0gF4/indian.webp",
  Chinese: "https://i.ibb.co/xSM8SWKd/chinese.webp",
  Continental: "https://i.ibb.co/gLPrn4Pk/continental.webp",
  Italian: "https://i.ibb.co/WvL1TRP6/italian.webp",
  Thai: "https://i.ibb.co/qL4n7L8t/thai.webp",
  American: "https://i.ibb.co/yc3GgckG/american.webp",
  Mediterranean: "https://i.ibb.co/ds4k6s2L/mediterrian.webp",
  Mexican: "https://i.ibb.co/JRvL1Yrp/mexican.webp",
  Turkish: "https://i.ibb.co/bgtgPvt5/turkish.webp",
  Persian: "https://i.ibb.co/Ps5nQwZP/persian.webp",
  Spanish: "https://i.ibb.co/PsqYk353/spanish.webp",
  French: "https://i.ibb.co/QvCM6XvY/french.webp",
  Japanese: "https://i.ibb.co/wFHXgVZ5/japanese.webp",
  Korean: "https://i.ibb.co/gZL2ZQCD/korean.webp",
};
