export const foodcategory = {
  Breakfast: "https://i.ibb.co/Tq764sQ4/breakfast.webp",
  Lunch: "https://i.ibb.co/qY4tzGvc/lunch.webp",
  Dinner: "https://i.ibb.co/mrRS1LQ0/dinner.webp",
  Snack: "https://i.ibb.co/53drtZ5/snack.webp",
  Brunch: "https://i.ibb.co/53drtZ5/snack.webp",
  Supper: "https://i.ibb.co/53drtZ5/snack.webp",
  "Tea Time": "https://i.ibb.co/53drtZ5/snack.webp",
  "Midnight Snack": "https://i.ibb.co/53drtZ5/snack.webp",
  Appetizer: "https://i.ibb.co/53drtZ5/snack.webp",
  Dessert: "https://i.ibb.co/53drtZ5/snack.webp",
  Beverage: "https://i.ibb.co/53drtZ5/snack.webp",
  "Side Dish": "https://i.ibb.co/53drtZ5/snack.webp",
  "Sea Food": "https://i.ibb.co/53drtZ5/snack.webp",
  "Street Food & Fast Food": "https://i.ibb.co/53drtZ5/snack.webp",
  "Healthy Meal": "https://i.ibb.co/53drtZ5/snack.webp",
};
